version: "3.8"

services:
  todolist-django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/todolistwebapp
      - todolist_static_volume:/todolistwebapp/static
      - todolist_media_volume:/todolistwebapp/media
    restart: always
    ports:
      - "8000:8000"
    networks:
      - todolist-webapp_network
    depends_on:
      - todolist-webapp_postgresql

  todolist-webapp_postgresql:
    image: postgres:12
    container_name: todolist-webapp_postgresql
    volumes:
      - todolist-webapp_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - todolist-webapp_network

volumes:
  todolist-webapp_postgresql:
    external: true
  todolist_static_volume:
    external: true
  todolist_media_volume:
    external: true

networks:
  todolist-webapp_network:
    external: true


