version: "3.8"

services:
  todolist-webapp_postgresql:
    image: postgres:12
    container_name: todolist-webapp_postgresql
    volumes:
      - todolist-webapp_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - todolist-webapp_network

volumes:
  todolist-webapp_postgresql:
    external: true

networks:
  todolist-webapp_network:
    external: true


